### PR TITLE
Add support for Sending System.Messaging.Message objects

### PR DESCRIPTION
**Pull request by arnoldpistorius**
Hi Stephen,

I have made changes to the code to add support for Message object.

See https://github.com/SteveBate/MiniBus/issues/7

### CODE REVIEW

**Comment by SteveBate** [comment]
Hi Arnold,

I don't think that wrapping the dto in a System.Messaging.Message instance is the right thing to do. Minibus should be abstracting away MSMQ. This feels a little hacky to me.

On the other hand, my thought was to add a TimeToBeReceived method to the BusBuilder fluent interface which would then ensure the value specified there was set on every message. This is my preferred approach and one I am just looking at right now.

**Comment by SteveBate** [comment]
TimeToBeReceived option has now been added to the BusBuilder fluent interface

**Comment by arnoldpistorius** [comment]
Thank you for your effort. Could you also update the nuget package?

**Comment by SteveBate** [comment]
Hi Arnold, I will do, just can't do it right now (work gets in the way!). It'll be up there soon though, hopefully sometime this week.

**Comment by SteveBate** [comment]
The nuget package has been [updated to 0.1.9](https://www.nuget.org/packages/Mini.Bus/0.1.9)

**Comment by arnoldpistorius** [comment]
Thank you, you're the best!

**Pull request closed without merging**
